version: 2.1
workflows:
  version: 2
  Deploying Tic Tac:
     jobs: 
      - test
      - build:
          requires:
            - test
jobs:
  test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
         name: installing Dependencies
         command: npm install
  build:
    docker:
      - image: cimg/node:14.17.3
    steps:
@@ -20,5 +28,4 @@ jobs:
      - run:
         name: build
         command: npm run build