version: 2.1
orbs:
  node: circleci/node@1.1
  
workflows:
  test-app:
    jobs:
       - test

jobs:
  test:
    docker:
     - image: cimg/node:14.13.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
               name: install dependencies
               command: npm install
            - run:
                name: run tests 
                command: npm run test
            - run: npm run build